services:
  rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
    environment:
      PASSWORD: x
      ROOT: true
    volumes:
      # - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace